stages:
  - build
  - tests
  - deploy

before_script:
  - echo `pwd`
  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE"
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - cd Backend/
    - sudo ./gradlew assemble
  tags:
    - BACKEND
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - main

tests:
  stage: tests
  tags:
    - BACKEND
  script:
    - cd Backend
    - sudo ./gradlew check

deploy:
  stage: deploy
  tags:
    - BACKEND
  script:
    - cd Backend/build/libs/
    - sudo systemctl stop httpd.service
    - sudo systemctl stop tomcat.service
    - java -jar goalfriend-0.0.1-SNAPSHOT.jar
