stages:
  - build_image
  - backend_test
  - backend_test

before_script:
  - docker info

build_image:
  stage: build_image
  tags:
    - BACKEND
    - FRONTEND  
  script:
    - cd Docker/
    - docker build --network=host -t "coms309"  -f Dockerfile.dockerfile .

backend_test:
  stage: backend_test
  tags:
    - BACKEND
  script:
    - cd Docker/
    - docker run --network=host --entrypoint /bin/bash coms309 -c ./backend_build.sh
    - docker cp coms309:"Backend/build/libs/goalfriend-0.0.1-SNAPSHOT.jar" " "~/deployment"

backend_test:
  stage: backend_test
  tags:
    - BACKEND
  script:
    - cd Docker/
    - docker run --network=host --entrypoint /bin/bash coms309 -c ./backend_test.sh