stages:
  - build
  - tests
  - deploy

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - cd Backend/
    - gradle assemble
    - ls -la
  tags:
    - BACKEND
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - main

tests:
  stage: tests
  tags:
    - BACKEND
  script:
    - cd Backend
    - gradle check

deploy:
  stage: deploy
  tags:
    - BACKEND
  script:
    - cd Backend/build/libs/
    - sudo systemctl stop httpd.service
    - sudo systemctl stop tomcat.service
    - java -jar goalfriend-0.0.1-SNAPSHOT.jar
