stages:
  - build_image
  # - backend_build
  # - backend_test
  - frontend_build
  - frontend_test
  - upload_artifacts

before_script:
  - docker info

build_image:
  stage: build_image
  tags:
    - BACKEND
    - FRONTEND  
  script:
    - cd Docker/
    - docker build --network=host -t "coms309"  -f Dockerfile.dockerfile .

# backend_build:
#   stage: backend_build
#   tags:
#     - BACKEND
#   script:
#     - cd Docker/
#     - docker run -v /home/gitlab-runner/artifacts:/artifacts --network=host --entrypoint /bin/bash coms309 -c ./backend_build.sh
#     - mkdir /home/gitlab-runner/builds/nACox5oU/0/cs309/fall2021/3_mc_5/artifacts/
#     - cp -r /home/gitlab-runner/artifacts/* /home/gitlab-runner/builds/nACox5oU/0/cs309/fall2021/3_mc_5/artifacts/

# backend_test:
#   stage: backend_test
#   tags:
#     - BACKEND
#   script:
#     - cd Docker/
#     - docker run --network=host --entrypoint /bin/bash coms309 -c ./backend_test.sh

frontend_build:
  stage: frontend_build
  tags:
    - FRONTEND
  script:
    - cd Docker/
    - docker run -v /home/gitlab-runner/artifacts:/artifacts --network=host --entrypoint /bin/bash coms309 -c ./frontend_build.sh
    - cp -r /home/gitlab-runner/artifacts/* /home/gitlab-runner/builds/nACox5oU/0/cs309/fall2021/3_mc_5/artifacts/

frontend_test:
  stage: frontend_test
  tags:
    - FRONTEND
  script:
    - cd Docker/
    - docker run --network=host --entrypoint /bin/bash coms309 -c ./frontend_test.sh

upload_artifacts:
  stage: upload_artifacts
  tags:
    - BACKEND,FRONTEND
  script:
    ls /home/gitlab-runner/builds/nACox5oU/0/cs309/fall2021/3_mc_5/artifacts/
  artifacts:
    paths:
      - /home/gitlab-runner/builds/nACox5oU/0/cs309/fall2021/3_mc_5/artifacts/*