stages:
  - build_image

before_script:
  - docker info

build_image:
  stage: build_image
  tags:
    - BACKEND
    - FRONTEND  
  script:
    - cd Docker/
    - docker build --network=host -t "coms309"  -f Dockerfile.dockerfile .
