before_script:
  - docker info

build_image:
  script:
    - git clone git@git.linux.iastate.edu:cs309/fall2021/3_mc_5.git
    - cd Docker/
    - docker build -t Dockerfile.dockerfile .
    - docker run Dockerfile
