variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  CI_DEBUG_SERVICES: trace

stages:
  - build
  - tests
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - cd Backend/
    - gradle assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - main

tests:
  stage: tests
  tags:
    - BACKEND
  script:
    - cd Backend
    - gradle check

deploy:
  stage: deploy
  tags:
    - BACKEND
  script:
    - cd Backend/build/libs/
    - java -jar goalfriend-0.0.1-SNAPSHOT.jar
