stages:
  - build
  - tests

build:
  stage: build
  script:
    - cd Backend/
    - gradle assemble
    - ls -la build/
    - ls -la build/libs
  tags:
    - BACKEND
  artifacts:
    paths:
      - libs/*.jar

tests:
  stage: tests
  tags:
    - BACKEND
  script:
    - cd Backend
    - gradle check
