stages:
  - gradlebuild
  - gradletests
  - deploy

gradlebuild:
  stage: gradlebuild
  tags:
    - BACKEND
  script:
    - cd Backend
    - gradle assemble
  artifacts:
    paths:
      - Backend/build/libs/goalfriend-0.0.1-SNAPSHOT.jar

gradletests:
  stage: gradletest
  tags:
    - BACKEND
  script:
    - cd Backend
    - gradle test
