stages:
  - build_image
  - backend_build
  - backend_test

before_script:
  - docker info

build_image:
  stage: build_image
  tags:
    - BACKEND
    - FRONTEND  
  script:
    - cd Docker/
    - docker build --network=host -t "coms309"  -f Dockerfile.dockerfile .

backend_build:
  stage: backend_build
  tags:
    - BACKEND
  script:
    - cd Docker/
    - docker run -v /home/gitlab-runner/artifacts:/artifacts --network=host --entrypoint /bin/bash coms309 -c ./backend_build.sh
    - ls /home/gitlab-runner/artifacts/
    - cp /home/gitlab-runner/artifacts/* `pwd`
  artifacts:
    paths:
      - `pwd`/*.jar

backend_test:
  stage: backend_test
  tags:
    - BACKEND
  script:
    - cd Docker/
    - docker run --network=host --entrypoint /bin/bash coms309 -c ./backend_test.sh