stages:
  - build_image
  - build_backend

before_script:
  - docker info

build_image:
  stage: build_image
  tags:
    - BACKEND
    - FRONTEND  
  script:
    - cd Docker/
    - docker build --network=host -t "coms309"  -f Dockerfile.dockerfile .

build_backend:
  stage: build_backend
  tags:
    - BACKEND
  script:
    - cd Docker/
    - docker run --network=host --entrypoint /bin/bash coms309 -c ./backend_build.sh